### ISSUE TITLE
CI/CD pipeline

### ISSUE THREAD

**Issue by Mr-Oregano** [FNBBDevs/nolang#28]
Create CI/CD pipeline using github actions. Might have unit tests, but definitely want an action to build an exe on release.

**Comment by ethanlchristensen** [comment]
made CICD to build nolnag exe, Need to package the build together so the exe can run

**Comment by nulzo** [comment]
I think this can be closed!

**Comment by nulzo** [comment]
> made CICD to build nolnag exe, Need to package the build together so the exe can run

erm... so then why is it not closed ? @ethanlchristensen 🤔 🤨
